---
- name: provisioning django_messages testapp
  hosts: localhost
  tasks:
  - name: Create Redis Container
    containers.podman.podman_container:
      name: myredis
      image: docker.io/library/redis
      command: redis-server --appendonly yes
      state: started
      recreate: yes
      publish:
        - 6379:6379
#      pod: django_messages_testapp
- name: "Running qcluster"
  hosts: localhost
  connection: local
  tasks:
  - name: "start qcluster"
    shell: "python django_messages/testapp/manage.py qcluster &"
    register: "output"
  - debug: var=output.stdout_lines