# Generated by Django 4.1.1 on 2022-10-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_messages', '0003_alter_message_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
